import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Navbar02 from "@/components/navbar-02/navbar-02";
import Footer01Page from "@/components/footer-01/footer-01";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     
      >
          <nav >
              <Navbar />
          </nav>
           <nav className="sticky top-0 z-50">
          <Navbar02 />
        </nav>
        {children}
       
          <Footer01Page />
        
      </body>
    </html>
  );
}
