export const asortiment = [
  { type: "group", title: "Арматура", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Арматура А3 рифленая" },
  { type: "item", title: "Арматура А1 Гладкая" },
  { type: "item", title: "Арматура композитная" },
  { type: "group", title: "Труба профильная", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Труба профильная квадратная" },
  { type: "item", title: "Труба профильная прямоугольная" },
  { type: "item", title: "Труба профильная оцинкованная" },
  { type: "group", title: "Трубы", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Труба электросварная" },
  { type: "item", title: "Труба водогазопроводная" },
  { type: "item", title: "Труба оцинкованная" },
  { type: "group", title: "Квадрат стальной" },
  { type: "item", title: "Квадрат стальной" },
  { type: "group", title: "Проволока", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Проволока" },
  { type: "group", title: "Балка двутавровая" },
  { type: "item", title: "Балка двутавровая" },
  { type: "group", title: "Уголок", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Равнополочный" },
  { type: "item", title: "Неравнополочный" },
  { type: "group", title: "Швеллер", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Швеллер" },
  { type: "item", title: "Швеллер гнутый" },
  { type: "group", title: "Лист металлический", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Лист стальной гладкий" },
  { type: "item", title: "Лист рифленый" },
  { type: "item", title: "Лист оцинкованный" },
  { type: "item", title: "Лист просечно-вытяжной" },
  { type: "group", title: "Полоса металлическая", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Полоса стальная" },
  { type: "item", title: "Полоса оцинкованная" },
  { type: "group", title: "Профнастил" },
  { type: "item", title: "Профнастил крашеный", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Профнастил оцинкованный" },
  { type: "group", title: "Металлический штакетник" },
  { type: "item", title: "Металлический штакетник" },
  { type: "group", title: "Отводы стальные", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Отводы неоцинкованные" },
  { type: "item", title: "Отводы оцинкованные" },
  { type: "group", title: "Сетка металлическая", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Сетка сварная в картах" },
  { type: "item", title: "Сетка сварная рулон" },
  { type: "item", title: "Сетка рабица" },
  { type: "item", title: "Сетка штукатурная (тканая)" },
  { type: "group", title: "Дополнительные материалы", image: "/images/armatura-a3.jpg" },
  { type: "item", title: "Заглушки для профильных труб" },
  { type: "item", title: "Фиксатор звездочка" },
  { type: "item", title: "Фиксатор стульчик" },
  { type: "item", title: "Петли" },
  { type: "item", title: "Саморезы" },
  { type: "item", title: "Электроды" },
];